runtime: python38

instance_class: F4

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic

handlers:
- url: /api/v1/.*
  script: auto

- url: /maintain/.*
  script: auto
  login: admin
