runtime: python38

instance_class: F4

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
